#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASS';
  CREATE DATABASE $APP_DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $APP_DB_NAME TO $APP_DB_USER;
  \connect $APP_DB_NAME $APP_DB_USER
  BEGIN;
    CREATE TABLE temperature(  
    id int NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    date TIMESTAMP NOT NULL,
    location VARCHAR (255) NOT NULL,
    temperature INT NOT NULL
);

CREATE TABLE humidity(
    id int NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    location VARCHAR (255) NOT NULL,
    date TIMESTAMP NOT NULL, 
    humidity INT NOT NULL
);
  COMMIT;
EOSQL